# Generated by Django 5.1.4 on 2025-01-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_course_department_alter_course_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, null=True, unique=True)),
                ('course_name', models.CharField(max_length=255, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_courses', to='accounts.department')),
                ('faculty_members', models.ManyToManyField(related_name='course_courses', to='accounts.faculty')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_courses', to='accounts.program')),
            ],
        ),
    ]
