# Generated by Django 5.1.4 on 2025-01-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_course_faculty_remove_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_members',
            field=models.ManyToManyField(related_name='departments', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='programs',
            field=models.ManyToManyField(related_name='departments_in', to='accounts.program'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs_in', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
